### ISSUE TITLE
Simply Awesome! Installation and Usage Examples?

### ISSUE THREAD

**Issue by zenny** [yantar92/org-capture-ref#1]
Hi @yantar92 

This is simply awesome with more scope than org-ref!

In addition, thanks for your invaluable inputs to https://www.reddit.com/r/orgmode/comments/j33yq2/workflow_for_notetaking_and_appending/

However, I could not find it in melpa/elpa!?

Any installation and usage instructions (could be a description of your own use case) in https://github.com/yantar92/org-capture-ref/blob/master/Readme.org or a screencast of your workflow, subject to your convenience, would be highly appreciated!

Cheers,
/z

**Comment by yantar92** [comment]
> However, I could not find it in melpa/elpa!?

It's only on github for now. I am still working on some important features [1].
Meanwhile, you may just download the package from github, place it into your `load-path` and require from your init file.

> Any installation and usage instructions (could be a description of your own use case) in https://github.com/yantar92/org-capture-ref/blob/master/Readme.org or a screencast of your workflow would be highly appreciated!

Isn't usage section describing how to use the package? 

I will add installation instructions and add a screencast later. Though screencast is probably too early to add. I need implement better integration with org-ref first.

[1] https://github.com/yantar92/org-capture-ref#planned-features

**Comment by zenny** [comment]
> > However, I could not find it in melpa/elpa!?
> 
> It's only on github for now. I am still working on some important features [1].

Simply exciting! :+1: 

> Meanwhile, you may just download the package from github, place it into your `load-path` and require from your init file.

Yep, shall do so. 

> > Any installation and usage instructions (could be a description of your own use case) in https://github.com/yantar92/org-capture-ref/blob/master/Readme.org or a screencast of your workflow would be highly appreciated!
> 
> Isn't usage section describing how to use the package?

Else, would you mind sharing your emacs config?

> 
> I will add installation instructions and add a screencast later.

Yay ho!

>  Though screencast is probably too early to add. I need implement better integration with org-ref first.

Eagerly look forward to.

Thanks again!

> 
> [1] https://github.com/yantar92/org-capture-ref#planned-features

**Comment by zenny** [comment]
So nice of you for updating (https://github.com/yantar92/org-capture-ref/commit/0b7b7e3c7d14e13a800628ba2addbdfbdeb6a2e1). 

However, I am trying to deploy `org-capture-ref` to scimax config which does not use `straight.el`, and therefore reports error, fyi.

```
Error (use-package): Failed to parse package asoc: use-package: Unrecognized keyword: :straight
```

**Comment by yantar92** [comment]
> Error (use-package): Failed to parse package asoc: use-package: Unrecognized keyword: :straight

See the updated code in Usage section

**Comment by yantar92** [comment]
> Else, would you mind sharing your emacs config?

https://github.com/yantar92/emacs-config

That's a complex beast. Note that Org-mode section is not necessarily readable. The notes are mostly for myself.

**Comment by zenny** [comment]
> > Else, would you mind sharing your emacs config?
> 
> https://github.com/yantar92/emacs-config
> 
> That's a complex beast. Note that Org-mode section is not necessarily readable. The notes are mostly for myself.

That serves the purpose.


> > Error (use-package): Failed to parse package asoc: use-package: Unrecognized keyword: :straight
> 
> See the updated code in Usage section

Thanks! Would you mind elaborating `(use package)` without `straight.el` to invoke `org-capture-ref`? Appreciate that.

**Comment by yantar92** [comment]
> Thanks! Would you mind elaborating (use package) without straight.el to invoke org-capture-ref? Appreciate that.

I tried my best to extend the Usage section. Let me know if something is still not clear.

P.S. Please, do not edit your comments too much after sending. I get the notifications by email and most likely see only the first version of the comments. If you add something quite different from the initial version, I may miss it.
