### ISSUE TITLE
Can `org-capture-ref-get-bibtex-from-first-doi` be later in the sequence?

### ISSUE THREAD

**Issue by c1-g** [yantar92/org-capture-ref#4]
If we reorder `org-capture-ref-get-bibtex-functions` so that site specific parsers come before `org-capture-ref-get-bibtex-from-first-doi`, will it eliminate the need for `org-capture-ref-mark-links-with-known-absent-doi` entirely?

**Comment by yantar92** [comment]
Sounds reasonable, but let me try it for a while on my side to see if the change breaks anything.
